ceph:
  mon:
    - hostname: zu-ceph-mon
      ip_man: 10.200.200.10
  node:
    - hostname: zu-ceph0
      ip_man: 10.200.200.11
      volume: ['vdb','vdc']
    - hostname: zu-ceph1
      ip_man: 10.200.200.12
      volume: ['vdb','vdc']
    - hostname: zu-ceph2
      ip_man: 10.200.200.13
      volume: ['vdb','vdc']
