---

- name: create user stack
  user:
    name: stack

- name: Create a 2048-bit SSH key for user stack in ~stack/.ssh/id_rsa
  user:
    name: stack
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Sudo without TTY
  template: 
    src: sudoers.j2
    dest: /etc/sudoers.d/stack
    validate: 'visudo -cf %s'
    mode: 0440

- name: Disable selinux
  shell: setenforce 0

- name: Disable selinux
  shell: sed -i 's/SELINUX\=enforcing/SELINUX\=permissive/g' /etc/selinux/config

